"""
Central service registry for AWS EOL Monitor.
Defines SERVICE_REGISTRY (metadata, guide URLs, field config) and exports
SERVICE_SLUG for backward compatibility with the collector.
"""

SERVICE_REGISTRY = {
    "Lambda": {
        "service_type":             "Lambda",
        "display_name":             "Lambda",
        "category":                 "Compute",
        "lifecycle_slug":           "aws-lambda",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html",
        "version_kind":             "runtime",
        "metadata_fields":          [],
    },
    "EC2": {
        "service_type":             "EC2",
        "display_name":             "EC2",
        "category":                 "Compute",
        "lifecycle_slug":           "amazon-linux",
        "lifecycle_source":         "inline",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/linux/al2023/ug/migrate-to-al2023.html",
        "version_kind":             "os",
        "metadata_fields":          ["instance_type", "ami_id", "image_name", "os_source", "platform_details",
                                     "ssm_managed", "ssm_agent_status", "ssm_platform_name",
                                     "ssm_platform_version", "ssm_platform_type", "ssm_computer_name",
                                     "scan_warning"],
    },
    "SageMakerNotebook": {
        "service_type":             "SageMakerNotebook",
        "display_name":             "SageMaker Notebook",
        "category":                 "Machine Learning",
        "lifecycle_slug":           "",
        "lifecycle_source":         "inline",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-al2-guide.html",
        "version_kind":             "platform",
        # Lifecycle note: platform_identifier strings (notebook-al1-v1, notebook-al2-v1/v2/v3,
        # notebook-al2023-v1) map to inline AWS retirement dates. AL1 retired December 2023.
        # AL2 support ends June 2026 (matches Amazon Linux 2 standard support end).
        # AL2023 is current with no announced EOL.
        "metadata_fields":          ["platform_identifier", "notebook_instance_status",
                                     "instance_type", "volume_size_in_gb",
                                     "direct_internet_access", "root_access"],
    },
    "ECSFargate": {
        "service_type":             "ECSFargate",
        "display_name":             "ECS Fargate",
        "category":                 "Containers",
        "lifecycle_slug":           "",
        "lifecycle_source":         "inline",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html",
        "version_kind":             "platform",
        "metadata_fields":          ["platform_version", "platform_family", "cluster_name",
                                     "service_status", "running_count", "desired_count", "launch_type"],
    },
    "EKS": {
        "service_type":             "EKS",
        "display_name":             "EKS",
        "category":                 "Containers",
        "lifecycle_slug":           "amazon-eks",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": True,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html",
        "version_kind":             "kubernetes",
        "metadata_fields":          ["platform_version", "cluster_status", "endpoint_public_access",
                                     "endpoint_private_access", "support_end_date", "final_eol_date"],
    },
    "RDS_mysql": {
        "service_type":             "RDS_mysql",
        "display_name":             "RDS MySQL",
        "category":                 "Database",
        "lifecycle_slug":           "amazon-rds-mysql",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": True,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html",
        "version_kind":             "engine",
        "metadata_fields":          ["engine", "db_instance_class", "db_instance_status", "support_end_date", "final_eol_date"],
    },
    "RDS_postgres": {
        "service_type":             "RDS_postgres",
        "display_name":             "RDS PostgreSQL",
        "category":                 "Database",
        "lifecycle_slug":           "amazon-rds-postgresql",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": True,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html",
        "version_kind":             "engine",
        "metadata_fields":          ["engine", "db_instance_class", "db_instance_status", "support_end_date", "final_eol_date"],
    },
    "RDS_postgresql": {
        "service_type":             "RDS_postgresql",
        "display_name":             "RDS PostgreSQL",
        "category":                 "Database",
        "lifecycle_slug":           "amazon-rds-postgresql",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": True,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html",
        "version_kind":             "engine",
        "metadata_fields":          ["engine", "db_instance_class", "db_instance_status", "support_end_date", "final_eol_date"],
    },
    "RDS_mariadb": {
        "service_type":             "RDS_mariadb",
        "display_name":             "RDS MariaDB",
        "category":                 "Database",
        "lifecycle_slug":           "amazon-rds-mariadb",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Upgrading.html",
        "version_kind":             "engine",
        "metadata_fields":          ["engine", "db_instance_class", "db_instance_status", "support_end_date", "final_eol_date"],
    },
    "Aurora_MySQL": {
        "service_type":             "Aurora_MySQL",
        "display_name":             "Aurora MySQL",
        "category":                 "Database",
        "lifecycle_slug":           "amazon-aurora-mysql",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": True,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.Patching.html",
        "version_kind":             "engine",
        "metadata_fields":          ["engine", "cluster_status", "engine_mode", "support_end_date", "final_eol_date"],
    },
    "Aurora_PostgreSQL": {
        "service_type":             "Aurora_PostgreSQL",
        "display_name":             "Aurora PostgreSQL",
        "category":                 "Database",
        "lifecycle_slug":           "amazon-aurora-postgresql",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": True,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Updates.Patching.html",
        "version_kind":             "engine",
        "metadata_fields":          ["engine", "cluster_status", "engine_mode", "support_end_date", "final_eol_date"],
    },
    "ElastiCache": {
        "service_type":             "ElastiCache",
        "display_name":             "ElastiCache",
        "category":                 "Caching",
        "lifecycle_slug":           "amazon-elasticache-redis",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/VersionManagement.html",
        "version_kind":             "engine",
        "metadata_fields":          [],
    },
    "AmazonMQ_ActiveMQ": {
        "service_type":             "AmazonMQ",
        "display_name":             "Amazon MQ (ActiveMQ)",
        "category":                 "Messaging",
        "lifecycle_slug":           "amazon-mq-activemq",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/activemq-version-management.html",
        "version_kind":             "engine",
        "metadata_fields":          ["engine_type", "broker_state", "deployment_mode",
                                     "auto_minor_version_upgrade", "broker_id"],
    },
    "AmazonMQ_RabbitMQ": {
        "service_type":             "AmazonMQ",
        "display_name":             "Amazon MQ (RabbitMQ)",
        "category":                 "Messaging",
        "lifecycle_slug":           "amazon-mq-rabbitmq",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/rabbitmq-version-management.html",
        "version_kind":             "engine",
        "metadata_fields":          ["engine_type", "broker_state", "deployment_mode",
                                     "auto_minor_version_upgrade", "broker_id"],
    },
    "DMS": {
        "service_type":             "DMS",
        "display_name":             "AWS DMS",
        "category":                 "Migration",
        "lifecycle_slug":           "aws-dms",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReleaseNotes.html",
        "version_kind":             "engine",
        "metadata_fields":          ["replication_instance_class", "replication_instance_status",
                                     "auto_minor_version_upgrade", "multi_az", "publicly_accessible",
                                     "allocated_storage"],
    },
    "MWAA": {
        "service_type":             "MWAA",
        "display_name":             "Amazon MWAA",
        "category":                 "Analytics",
        "lifecycle_slug":           "apache-airflow",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html",
        "version_kind":             "airflow",
        # Lifecycle note: MWAA runs Apache Airflow. endoflife.date tracks apache-airflow
        # cycles (major.minor). AWS MWAA support end dates are verified separately via
        # the verified_lifecycle table (AWS official MWAA version support docs).
        "metadata_fields":          ["airflow_version", "environment_class", "environment_status",
                                     "webserver_access_mode", "max_workers", "min_workers",
                                     "schedulers"],
    },
    "MSK": {
        "service_type":             "MSK",
        "display_name":             "MSK",
        "category":                 "Streaming",
        "lifecycle_slug":           "amazon-msk",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/msk/latest/developerguide/version-upgrades.html",
        "version_kind":             "kafka",
        "metadata_fields":          ["kafka_version", "cluster_state", "broker_node_count", "current_version"],
    },
    "CodeBuild": {
        "service_type":             "CodeBuild",
        "display_name":             "CodeBuild",
        "category":                 "Developer Tools",
        "lifecycle_slug":           "",
        "lifecycle_source":         "metadata",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "LIFECYCLE_NOT_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html",
        "version_kind":             "build_image",
        "metadata_fields":          ["codebuild_image", "environment_type", "compute_type", "privileged_mode"],
    },
    "ElasticBeanstalk": {
        "service_type":             "ElasticBeanstalk",
        "display_name":             "Elastic Beanstalk",
        "category":                 "Compute",
        "lifecycle_slug":           "",
        "lifecycle_source":         "aws_api",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.platform.upgrade.html",
        "version_kind":             "platform",
        # Lifecycle: PlatformLifecycleState from describe_platform_version (supported/deprecated/retired).
        # Falls back to OS-based inline table when ARN absent or describe unavailable.
        "metadata_fields":          ["application_name", "environment_name", "environment_id",
                                     "environment_status", "health", "tier", "version_label",
                                     "platform_arn", "platform_branch_name",
                                     "platform_lifecycle_state", "solution_stack_name"],
    },
    "EMR": {
        "service_type":             "EMR",
        "display_name":             "EMR",
        "category":                 "Analytics",
        "lifecycle_slug":           "",
        "lifecycle_source":         "metadata",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "LIFECYCLE_NOT_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-release-components.html",
        "version_kind":             "release_label",
        "metadata_fields":          ["cluster_id", "release_label", "cluster_state", "applications"],
    },
    "OpenSearch": {
        "service_type":             "OpenSearch",
        "display_name":             "OpenSearch",
        "category":                 "Search",
        "lifecycle_slug":           "amazon-opensearch",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/version-migration.html",
        "version_kind":             "engine",
        "metadata_fields":          [],
    },
    "DocumentDB": {
        "service_type":             "DocumentDB",
        "display_name":             "DocumentDB",
        "category":                 "Database",
        "lifecycle_slug":           "amazon-documentdb",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/documentdb/latest/developerguide/upgrading.html",
        "version_kind":             "engine",
        "metadata_fields":          [],
    },
    "Neptune": {
        "service_type":             "Neptune",
        "display_name":             "Neptune",
        "category":                 "Database",
        "lifecycle_slug":           "amazon-neptune",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases.html",
        "version_kind":             "engine",
        "metadata_fields":          [],
    },
    "Glue": {
        "service_type":             "Glue",
        "display_name":             "Glue",
        "category":                 "Analytics",
        "lifecycle_slug":           "amazon-glue",
        "lifecycle_source":         "endoflife.date",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/glue/latest/dg/release-notes.html",
        "version_kind":             "glue",
        "metadata_fields":          ["glue_version", "python_version", "spark_version", "worker_type",
                                     "command_name", "command_script_location"],
    },
    "CloudFrontFunctions": {
        "service_type":             "CloudFrontFunctions",
        "display_name":             "CloudFront Functions",
        "category":                 "Edge",
        "lifecycle_slug":           "",
        "lifecycle_source":         "metadata",
        "supports_extended_support": False,
        "lifecycle_applicable":     False,
        "classification_type":      "NOT_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html",
        "version_kind":             "runtime",
        "metadata_fields":          ["function_runtime", "function_stage", "function_status"],
    },
    "AWSBatch": {
        "service_type":             "AWSBatch",
        "display_name":             "AWS Batch",
        "category":                 "Compute",
        "lifecycle_slug":           "",
        "lifecycle_source":         "inline",
        "supports_extended_support": False,
        "lifecycle_applicable":     True,
        "classification_type":      "EOL_TRACKED",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/batch/latest/userguide/batch-supported-iam-actions-resources.html",
        "version_kind":             "ami_type",
        # Lifecycle: ec2Configuration.imageType classifies against AL2/AL2023 AMI support dates.
        # AL2 ECS/EKS-optimized AMIs follow Amazon Linux 2 standard support (ends 2026-06-30).
        # AL2023 variants are current with no announced EOL.
        # Custom imageId without imageType cannot be safely classified → NEEDS_INSPECTION.
        "metadata_fields":          ["compute_environment_name", "compute_environment_arn",
                                     "type", "state", "status", "status_reason",
                                     "compute_resources_type", "allocation_strategy",
                                     "min_vcpus", "max_vcpus", "desired_vcpus",
                                     "instance_types", "image_id", "image_type",
                                     "ec2_configuration", "eks_configuration", "service_role"],
    },
    "ECR": {
        "service_type":             "ECR",
        "display_name":             "ECR",
        "category":                 "Containers",
        "lifecycle_slug":           "",
        "lifecycle_source":         "metadata",
        "supports_extended_support": False,
        "lifecycle_applicable":     False,
        "classification_type":      "INVENTORY_ONLY",
        "default_aws_guide_url":    "https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html",
        "version_kind":             "image_tag",
        "metadata_fields":          ["repository_name", "image_tag", "image_digest", "short_digest",
                                     "image_pushed_at", "image_size_in_bytes", "base_image_status"],
    },
}

# Backward-compatible dict — same keys/values as the original inline SERVICE_SLUG in eol_collector.py.
# Collector imports from here; do not reorder or rename keys without updating the collector.
SERVICE_SLUG: dict[str, str] = {
    "Lambda":          "aws-lambda",
    "EKS":             "amazon-eks",
    "RDS_mysql":       "amazon-rds-mysql",
    "RDS_postgres":    "amazon-rds-postgresql",
    "RDS_mariadb":     "amazon-rds-mariadb",
    "Aurora_postgres": "amazon-aurora-postgresql",
    "Aurora_mysql":    "amazon-aurora-mysql",
    "ElastiCache":     "amazon-elasticache-redis",
    "Valkey":          "amazon-elasticache-valkey",
    "AmazonMQ_ActiveMQ": "amazon-mq-activemq",
    "AmazonMQ_RabbitMQ": "amazon-mq-rabbitmq",
    "DMS":             "aws-dms",
    "MWAA":            "apache-airflow",
    "EC2":             "amazon-linux",
    "MSK":             "amazon-msk",
    "OpenSearch":      "amazon-opensearch",
    "DocumentDB":      "amazon-documentdb",
    "Neptune":         "amazon-neptune",
    "Glue":            "amazon-glue",
}
